# Generated by Django 3.0.8 on 2020-07-29 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fanservice', '0003_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficialPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('imp', models.ImageField(upload_to='images')),
                ('post', models.CharField(max_length=140)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.RenameModel(
            old_name='Post',
            new_name='NormalPost',
        ),
    ]
